# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDistrict',
            fields=[
                ('district', models.CharField(max_length=255)),
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('city', models.CharField(max_length=255, null=True)),
                ('party', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionvote', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hvote', to='main.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('photolink', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SenateDistrict',
            fields=[
                ('district', models.CharField(max_length=255)),
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('city', models.CharField(max_length=255, null=True)),
                ('party', models.CharField(max_length=255, null=True)),
                ('incumbent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='main.Politician')),
            ],
        ),
        migrations.CreateModel(
            name='SenateVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionvote', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svote', to='main.Bill')),
                ('senatemember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Politician')),
            ],
        ),
        migrations.AddField(
            model_name='housevote',
            name='housemember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Politician'),
        ),
        migrations.AddField(
            model_name='housemember',
            name='incumbent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Politician'),
        ),
        migrations.AddField(
            model_name='housedistrict',
            name='incumbent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd', to='main.Politician'),
        ),
    ]
