# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171127_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='zipcode',
            field=models.CharField(max_length=255),
        ),
    ]
