# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171127_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='client_ip',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
