# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_capture_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='client_ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
